import assert from 'node:assert/strict';
import { defaultCatalog } from '../src/admin/catalog';
import { estimateQuote } from '../server/quoteEngine';
import type { QuoteSelection } from '../src/types/quote';

const catalog=defaultCatalog();
const pkg=catalog.packages[0];
const selection:QuoteSelection={eventType:'cena_privada',eventDate:'2099-06-15',zoneId:catalog.zones[0].id,packageId:pkg.id,guestsCount:10,selectedExtras:{}};
const result=estimateQuote(catalog,selection);
assert.equal(result.breakdown.totalEstimatedCents,10*pkg.pricePerPersonCents+catalog.zones[0].travelFeeCents);
assert.equal(result.estimateStatus,'partial');assert.equal(result.demo,true);
for(const guestsCount of [0,-1,1.5,151,NaN,Infinity,'10',null])assert.throws(()=>estimateQuote(catalog,{...selection,guestsCount}));
for(const eventDate of ['2026-02-30','2099-02-30','not-date','2000-01-01'])assert.throws(()=>estimateQuote(catalog,{...selection,eventDate}));
assert.throws(()=>estimateQuote(catalog,{...selection,packageId:'missing'}));
assert.throws(()=>estimateQuote(catalog,{...selection,zoneId:'missing'}));
assert.throws(()=>estimateQuote(catalog,{...selection,eventType:'missing'}));
assert.throws(()=>estimateQuote(catalog,{...selection,totalEstimatedCents:1}));
assert.throws(()=>estimateQuote(catalog,{...selection,selectedExtras:{missing:1}}));
assert.throws(()=>estimateQuote(catalog,{...selection,selectedExtras:[]}));
for(const extra of catalog.extras) {
  const p=catalog.packages.find(p=>p.compatibleExtraIds.includes(extra.id))!;
  const s={...selection,packageId:p.id,selectedExtras:{[extra.id]:extra.pricingType==='per_unit'?2:1}};
  const e=estimateQuote(catalog,s).breakdown.extrasItemized[0];
  assert.equal(e.totalCents,extra.priceCents*(extra.pricingType==='per_person'?10:extra.pricingType==='per_unit'?2:1));
  for(const quantity of [0,-1,0.5,999])assert.throws(()=>estimateQuote(catalog,{...s,selectedExtras:{[extra.id]:quantity}}));
  if(extra.pricingType!=='per_unit')assert.throws(()=>estimateQuote(catalog,{...s,selectedExtras:{[extra.id]:2}}));
  const incompatible=catalog.packages.find(p=>!p.compatibleExtraIds.includes(extra.id));
  if(incompatible)assert.throws(()=>estimateQuote(catalog,{...s,packageId:incompatible.id}));
}
const low=estimateQuote(catalog,{...selection,guestsCount:1});
assert.equal(low.breakdown.menuSubtotalCents,pkg.pricePerPersonCents);assert.equal(low.breakdown.minGuestsWarning,true);
const pending=catalog.zones.find(z=>z.requiresConfirmation)!;
assert.equal(estimateQuote(catalog,{...selection,zoneId:pending.id}).breakdown.travelRequiresConfirmation,true);
const changed=structuredClone(catalog);changed.packages[0].pricePerPersonCents++;
assert.notEqual(result.version,estimateQuote(changed,selection).version);
assert.equal(result.breakdown.selectedPackage!.pricePerPersonCents,pkg.pricePerPersonCents);
console.log('OK: cálculo servidor, enteros, fechas, IDs, compatibilidad, límites, mínimos y versiones.');

const now=new Date('2099-06-01T18:00:00Z');
const answers={investment:'fits',requirements:'yes',dietaryReview:false};
const rules=structuredClone(catalog);
const lead=rules.rules.leadTimes.find(r=>r.id===pkg.id)!;
lead.days=15;
const s={...selection,commercial:answers};
assert.equal(estimateQuote(rules,s,now).qualification!.status,'ready');
lead.approved=true;
assert.equal(estimateQuote(rules,s,now).qualification!.status,'clarify');
lead.days=14;
assert.equal(estimateQuote(rules,s,now).qualification!.status,'ready');
rules.rules.requirementsApproved=true;
rules.rules.requirementsText='Cocina de prueba';
assert.equal(estimateQuote(rules,{...s,commercial:{...answers,requirements:'no'}},now).qualification!.status,'clarify');
assert.equal(estimateQuote(rules,{...s,commercial:{...answers,investment:'review'}},now).qualification!.status,'clarify');
assert.equal(estimateQuote(rules,{...s,commercial:{...answers,dietaryReview:true}},now).qualification!.status,'clarify');
assert.equal(estimateQuote(rules,{...s,zoneId:pending.id},now).qualification!.status,'clarify');
assert.throws(()=>estimateQuote(rules,{...s,commercial:{...answers,investment:['fits']}},now));
assert.throws(()=>estimateQuote(rules,{...s,commercial:{...answers,score:90}},now));
const beforeRules=estimateQuote(rules,s,now);
rules.rules.validityDays=10;rules.rules.validityApproved=true;
const afterRules=estimateQuote(rules,s,now);
assert.notEqual(beforeRules.version,afterRules.version);
assert.equal(beforeRules.rulesSnapshot!.validityApproved,false);
assert.equal(afterRules.rulesSnapshot!.validityDays,10);
assert.equal(afterRules.breakdown.totalEstimatedCents,beforeRules.breakdown.totalEstimatedCents);
console.log('OK: reglas pendientes/aprobadas, anticipación al límite, requisitos, inversión, restricciones y snapshots.');
