const assert = require('node:assert/strict');
const fs = require('node:fs');
const ts = require('typescript');
require.extensions['.ts'] = (module, filename) => {
  const source = fs.readFileSync(filename, 'utf8');
  module._compile(ts.transpileModule(source, { compilerOptions: { module: ts.ModuleKind.CommonJS } }).outputText, filename);
};
const { getStepErrors, isQuoteReady } = require('../src/utils/validation.ts');
const { calculateQuote, pruneIncompatibleExtras } = require('../src/utils/calculator.ts');
const { generateWhatsAppUrl } = require('../src/utils/whatsapp.ts');
const { DEMO_PACKAGES, EVENT_TYPES } = require('../src/config/packages.ts');
const { ZONES_CONFIG } = require('../src/config/zones.ts');
const { EXTRAS_CONFIG } = require('../src/config/extras.ts');
const { getTodayMinDateString } = require('../src/utils/formatters.ts');
const state = { eventType: EVENT_TYPES[0].id, eventDate: getTodayMinDateString(), zoneId: ZONES_CONFIG[0].id, packageId: DEMO_PACKAGES[0].id, guestsCount: 6, selectedExtras: {}, clientName: 'Prueba & Validación', dietaryRestrictions: '', additionalNotes: '' };
assert.equal(isQuoteReady(state), true);
for (const eventDate of ['', '2000-01-01', '2099-02-30', 'invalid']) assert.equal(isQuoteReady({...state, eventDate}), false);
const today = new Date();
const todayString = `${today.getFullYear()}-${String(today.getMonth()+1).padStart(2,'0')}-${String(today.getDate()).padStart(2,'0')}`;
assert.equal(isQuoteReady({...state,eventDate:todayString}),false);
for (const guestsCount of [0, -1, 1.5, 151, NaN, Infinity]) assert.ok(getStepErrors({...state, guestsCount}, 2).guestsCount);
assert.equal(isQuoteReady({...state,clientName:'   '}),false);
assert.equal(isQuoteReady({...state,packageId:'missing'}),false);
assert.equal(isQuoteReady({...state,zoneId:'missing'}),false);
const before = JSON.stringify(state);
getStepErrors(state,1);
assert.equal(JSON.stringify(state),before);
for (const pkg of DEMO_PACKAGES) {
  if (pkg.maxGuests) {
    assert.ok(getStepErrors({...state, packageId:pkg.id,guestsCount:pkg.maxGuests+1},2).guestsCount);
    assert.equal(getStepErrors({...state, packageId:pkg.id,guestsCount:pkg.maxGuests},2).guestsCount,undefined);
  }
  const selectedExtras = Object.fromEntries(EXTRAS_CONFIG.map(extra=>[extra.id,extra.pricingType==='per_unit'?2:1]));
  const quoteState = {...state,packageId:pkg.id,selectedExtras};
  const quote = calculateQuote(quoteState);
  const expectedExtras = EXTRAS_CONFIG.filter(extra=>pkg.compatibleExtraIds.includes(extra.id)).reduce((sum,extra)=>sum+extra.priceCents*(extra.pricingType==='per_person'?6:extra.pricingType==='per_unit'?2:1),0);
  assert.equal(quote.totalEstimatedCents,pkg.pricePerPersonCents*6+expectedExtras+ZONES_CONFIG[0].travelFeeCents);
  assert.ok(Object.keys(pruneIncompatibleExtras(pkg.id,selectedExtras)).every(id=>pkg.compatibleExtraIds.includes(id)));
  const whatsapp = generateWhatsAppUrl(quoteState,quote);
  assert.equal(new URL(whatsapp.url).searchParams.get('text'),whatsapp.rawMessage);
}
const pending = ZONES_CONFIG.find(zone=>zone.requiresConfirmation);
assert.equal(calculateQuote({...state,zoneId:pending.id}).travelRequiresConfirmation,true);
console.log('OK: fechas, límites de invitados, campos obligatorios, cálculos de todos los menús, extras, traslado y URL de WhatsApp.');

const { createDefaultQuote, serializeDraft, restoreDraft, quoteReducer, DRAFT_TTL_MS } = require('../src/utils/quoteDraft.ts');
const now = Date.now();
const personalQuote = {...state, clientName: 'PRIVATE_NAME', dietaryRestrictions: 'PRIVATE_ALLERGY', additionalNotes: 'PRIVATE_NOTE', guestsCount: 12};
const serialized = serializeDraft(personalQuote, now);
for (const secret of ['PRIVATE_NAME', 'PRIVATE_ALLERGY', 'PRIVATE_NOTE', 'clientName', 'dietaryRestrictions', 'additionalNotes']) assert.ok(!serialized.includes(secret));
const restored = restoreDraft(serialized, now);
assert.equal(restored.guestsCount,12);
assert.equal(restored.eventDate,state.eventDate);
assert.equal(restored.clientName,'');
assert.equal(restored.dietaryRestrictions,'');
assert.equal(restored.additionalNotes,'');
assert.equal(restoreDraft(serialized,now + DRAFT_TTL_MS + 1),null);
assert.equal(restoreDraft(serialized,now - 1),null);
for (const raw of ['bad json','null','[]','{}','x'.repeat(16001)]) assert.equal(restoreDraft(raw,now),null);
const altered = JSON.parse(serialized);
altered.version = 999;
assert.equal(restoreDraft(JSON.stringify(altered),now),null);
altered.version = 1;
altered.catalogVersion = 'old-catalog';
assert.equal(restoreDraft(JSON.stringify(altered),now),null);
altered.catalogVersion = 'demo-v1';
altered.selection = {...altered.selection, packageId:'deleted', zoneId:'deleted', eventType:'deleted', guestsCount:1e99, eventDate:'2000-01-01', clientName:'MALICIOUS', selectedExtras:{'mesero-adicional':99}};
const sanitized = restoreDraft(JSON.stringify(altered),now);
assert.equal(sanitized.packageId,DEMO_PACKAGES[0].id);
assert.equal(sanitized.guestsCount,6);
assert.equal(sanitized.eventDate,'');
assert.equal(sanitized.clientName,'');
assert.deepEqual(sanitized.selectedExtras,{});
const withExtras = {...personalQuote,selectedExtras:Object.fromEntries(EXTRAS_CONFIG.map(extra=>[extra.id,1]))};
const beforeSession = {quote:withExtras,notice:''};
const changed = quoteReducer(beforeSession,{type:'field',field:'packageId',value:DEMO_PACKAGES[1].id});
assert.equal(changed.quote.clientName,personalQuote.clientName);
assert.equal(changed.quote.eventDate,personalQuote.eventDate);
assert.equal(changed.quote.guestsCount,12);
assert.equal(changed.quote.dietaryRestrictions,'PRIVATE_ALLERGY');
assert.ok(Object.keys(changed.quote.selectedExtras).every(id=>DEMO_PACKAGES[1].compatibleExtraIds.includes(id)));
assert.ok(changed.notice.includes('retiramos'));
assert.equal(quoteReducer(changed,{type:'field',field:'packageId',value:'unknown'}),changed);
const experience = quoteReducer(changed,{type:'field',field:'eventType',value:'celebracion'});
assert.equal(experience.quote.eventDate,state.eventDate);
assert.equal(experience.quote.clientName,personalQuote.clientName);
const reset = quoteReducer(experience,{type:'reset'});
assert.deepEqual(reset.quote,createDefaultQuote());
assert.deepEqual(restoreDraft(serializeDraft(reset.quote,now),now),createDefaultQuote());
const bounded = JSON.parse(serializeDraft(state,now));
bounded.selection.selectedExtras={'mesero-adicional':999,'maridaje-vinos':-1,'unknown':1};
assert.deepEqual(restoreDraft(JSON.stringify(bounded),now).selectedExtras,{'mesero-adicional':5});
console.log('OK: borrador privado, expiración, datos corruptos, catálogo obsoleto, límites, cambios de menú/experiencia y reinicio.');
