CREATE TABLE IF NOT EXISTS editorial_state (
  id TINYINT PRIMARY KEY,
  revision BIGINT UNSIGNED NOT NULL,
  document LONGTEXT NOT NULL CHECK (JSON_VALID(document))
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS staff_users (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(254) NOT NULL UNIQUE,
  name VARCHAR(80) NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  role ENUM('owner','editor','sales') NOT NULL,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS staff_sessions (
  sid VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin PRIMARY KEY,
  expires_at BIGINT NOT NULL,
  document LONGTEXT NOT NULL CHECK (JSON_VALID(document)),
  INDEX session_expiry (expires_at)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS editorial_audit (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  actor_id INT UNSIGNED NOT NULL,
  action VARCHAR(24) NOT NULL,
  revision BIGINT UNSIGNED NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (actor_id) REFERENCES staff_users(id)
) ENGINE=InnoDB;
